import 'dart:async';
import 'package:flutterstackapp/home/index.dart';
import 'package:meta/meta.dart';

/// Interface for events generated by the Home Page
@immutable
abstract class HomeEvent {
  Future<HomeState> applyAsync({HomeState currentState, HomeBloc bloc});
  final HomeProvider _homeProvider = new HomeProvider();
}

/// This event indicates 'Home Page loaded'
class LoadHomeEvent extends HomeEvent {
  @override
  String toString() => 'LoadHomeEvent';

  @override
  Future<HomeState> applyAsync({HomeState currentState, HomeBloc bloc}) async {
    try {
      QuestionData res = await _homeProvider.getData();
      // Return the 'Initialised Home Page state' with data from Stack overflow
      return new InHomeState(res);
    } catch (_) {
      print('LoadHomeEvent ' + _?.toString());
      return new ErrorHomeState(_?.toString());
    }
  }
}
